version: '3'

services:

    db:
      image: postgres

      restart: always

      volumes:
        - ./goinfre/mhaddaou/app_nest_next/my_b/db

      ports:
        - 5432:5432

      environment:
        - POSTGRES_DB=testdb
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=said123

    adminer:
      image: adminer

      restart: always

      ports:
        - 8080:8080
